apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
spec:
  type: NodePort
  selector:
    app: python-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32443
