apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: elk-demo-cluster
  region: us-east-1
  version: "1.27"
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 4
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        cloudWatch: true
